# .github/workflows/combined.yml
name: Run Script on Schedule or Push

on:
  schedule:
    - cron: '0 * * * *'  # 每1小时执行
  push:
    branches:
      - main  # 当 main 分支有变动时触发
  pull_request:
    branches:
      - main  # 当 PR 更新时触发

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run a script
        run: |
          echo "Running script on schedule or push"
          ./deploy.sh
